fix modal
PoliNetworkOrg/PoliFemo pull request #143
Opened 2023-02-16 17:52 UTC by DiegoZaff

2023-02-16 17:52 UTC, PoliNetwork-ClickUp commented
Task linked: [CU-8669hvbce La status bar cambia colore dentro i modali](https://app.clickup.com/t/8669hvbce)

2023-02-21 08:15 UTC, toto04 submitted a review, later dismissed

2023-02-21 08:37 UTC, toto04 requested changes
non vedo l'ora finiscano i branch aperti prima del cambio di indentazione ahah
comunque ModalSelect lì come si chiamava a un certo punto è stato sostituito con ModalWithButtons, modifica anche quello come gli altri

2023-02-21 08:37 UTC, toto04 commented on src/components/Modal.tsx
> +        animationOutTiming={props.animationTiming ?? 100}
100 come default magari è un po' troppo veloce, forse qualcosa come 200ms è meglio no?

2023-02-21 16:16 UTC, DiegoZaff commented on src/components/Modal.tsx
> +        animationOutTiming={props.animationTiming ?? 100}
Ok si

2023-02-21 16:47 UTC, DiegoZaff commented
Ho anche fixato un bug che ho notato aumentando la durata dell'animazione per il quale la shadow non veniva animata ed era molto brutto. Quanto pare è solo un problema di android. C'è un workaround che ho trovato in questa [issue](https://github.com/facebook/react-native/issues/23090)

2023-02-21 16:50 UTC, DiegoZaff commented
Nel branch dello Slider Immagini e in quello del dettaglio aula ci sono degli altri modali da modificare mi pare. Li modifico singolarmente nei rispettivi branch va bene?

2023-02-21 17:31 UTC, toto04 commented
sì fai un merge da main e poi modifichi come ritieni opportuno direi

2023-02-21 17:32 UTC, toto04 approved these changes

2023-02-21 17:32 UTC, merged