Fix Shadows
PoliNetworkOrg/PoliFemo pull request #177
Opened 2023-02-26 17:43 UTC by toto04

ho fixato le ombre :)

praticamente al posto di usare le API native per le ombre che fanno completamente schifo, viene creato un svg programmaticamente che casta un'ombra dietro di se, questo svg viene renderizzato da Skia e deve essere messo in position absolute dietro a una view che copre il vero e proprio svg

🤯 

ho creato un componente `BoxShadowView` che è una view con sta cosa delle ombre e un'altra view che copre sto svg per aiutare nella maggior parte dei casi, se no `BoxShadowCanvas` è letteralmente il canvas che fa il rendering dell'svg

mo'devo solo metterle in tutti gli altri posti lol

2023-02-26 17:43 UTC, PoliNetwork-ClickUp commented
Task linked: [CU-8669jr0nh [BUG] News modal behavior is not clear](https://app.clickup.com/t/8669jr0nh)

2023-03-05 05:55 UTC, toto04 commented
Ok allora, principalmente lo scopo di questa PR era aggiungere i file che si trovano in `src/components/BoxShadow`, ma mi sono fatto prendere la mano, perché per cose tipo i modali dovevo programmaticamente prendere le dimensioni dal layout e c'era un bug in Skia che faceva animare i path degli svg anche se non volevi quindi era tutto bruttissimo, mi è servito upgradare tutti i pacchetti via expo 48 per questo.

comunque quando ho modificato un modale mi sono reso conto che ce ne sono mille e invece di modificarli tutti li ho buttati via e ho reso Modal.tsx più riutilizzabile, quindi ho un po' massacrato qualsiasi punto avesse un modale, tutti i modali che vengono usati in app dovrebbero al loro interno usare quello principale (in Modal.tsx), in caso piuttosto che creare un nuovo componente si aggiungono props, ModalWithButtons è stato distrutto, c'è un props buttons nel Modal normale ora, stesso vale per ModalGroup che era inutile perché solo un copia incolla di Modal con dentro ModalGroupItem che boh, ho reso tutto un componente solo che usa Modal al suo interno passando un'icona come opzione

`AdaptiveShadowView` è un componente che prende le dimensioni delle ombre dal layout, molto pratico ma non troppo performante e l'ombra appare solo a un secondo render, quindi non ideale in molti punti

Ho dovuto spostare il SettingsContext Provider in App.tsx all'esterno di Host perché se no nei modali il context delle impostazioni non veniva consumato correttamente

Ho anche modificato un colore di default del componente Button che era sbagliato lol

L'unica cosa che usa ancora le ombre native è la search bar dato che non ho implementato alcuna forma di animazione nella mia ombra, sarebbe estremamente impestato e non mi sembra ne valga la pena rn, si può fare in un altro momento

2023-03-05 10:53 UTC, DiegoZaff commented
Succede qualcosa di strano con il modale. A volte si apre correttamente, a volte si apre mostrando un rettangolo bianco totalmente a caso.

Succede anche a voi?

![Screenshot_2023-03-05-11-47-54-947_host.exp.exponent.jpg](https://user-images.githubusercontent.com/43524162/222956069-3ae45a4e-0495-455e-85c0-a314760f366f.jpg)

2023-03-05 10:56 UTC, bob27aggiustatutto commented
> Succede qualcosa di strano con il modale. A volte si apre correttamente, a volte si apre mostrando un rettangolo bianco totalmente a caso.
> 
> Succede anche a voi?
> 
> ![Screenshot_2023-03-05-11-47-54-947_host.exp.exponent.jpg](https://user-images.githubusercontent.com/43524162/222956069-3ae45a4e-0495-455e-85c0-a314760f366f.jpg)

E in più, mi sembra di vedere/capire, la barra sotto (quella con quadrato, cerchio, triangolo) è bianca e non dovrebbe esserlo

2023-03-05 17:07 UTC, toto04 commented
> Succede qualcosa di strano con il modale. A volte si apre correttamente, a volte si apre mostrando un rettangolo bianco totalmente a caso.
> 
> Succede anche a voi?

Per quanto abbia provato, non sembra riproducibile su iOS, ho provato su emulatore Android e il comportamento sembra completamente casuale, ho cercato di debuggare il possibile e ad occhio e croce sembra un bug in Skia (sempre colpa degli altri ikr 🙄), la posizione del canvas è giusta, è la posizione dell'SVG all'interno del canvas che è a caso nonostante tutte le dimensioni in javascript siano giuste (btw, il rettangolo bianco è ciò che casta l'ombra, l'ho fatto bianco giusto perché se si vede è comunque un errore, tanto vale dia nell'occhio, deve venire sempre nascosto da una View sovrapposta perché sta cosa funzioni)

Comunque credo che sia un problema derivato dal cambio di dimensione del canvas tra due render consecutivi, perciò ho aggiunto una riga che non fa affatto renderizzare il canvas se le dimensioni sono a 0 (valore di default prima del layout event), e non sono più riuscito a riprodurlo, quindi credo sia un fix? spero ahah? @DiegoZaff prova intensamente a cliccare un sacco di volte il modale per vedere se ti riappare



> E in più, mi sembra di vedere/capire, la barra sotto (quella con quadrato, cerchio, triangolo) è bianca e non dovrebbe esserlo

Non c'entra nulla lol, quella sicuro non è stata toccata da nessuna parte in questa PR

2023-03-05 17:24 UTC, DiegoZaff commented
Non si vede più il rettangolo bianco ma l'ombra sembra tagliata

![Screenshot_2023-03-05-18-22-51-433_host.exp.exponent.jpg](https://user-images.githubusercontent.com/43524162/222975864-c2fb3abb-a63e-48e6-985a-22a5b08e1a7e.jpg)

2023-03-05 18:07 UTC, toto04 commented
okok, sembra che react-native-modal avesse qualche sorta di margine di default (?), da lì solito di scorso di Android che clippa le cose fuori dal margine e iOS no, modificato un po' lo sitle per accomodare questa cosa, controlla adesso

2023-03-05 18:15 UTC, DiegoZaff commented
Perfetto, x i modali sembra risolto.

Ti faccio presente invece un altra cosa che ho notato, l'ombra di alcuni componenti sono un po' troppo chiare e su fondo scuro sono un po' strane. Ad esempio il wrapper della pagina dei gruppi o lo slide degli articoli. 

Ad esempio:![Screenshot_2023-03-05-19-12-53-631_host.exp.exponent.jpg](https://user-images.githubusercontent.com/43524162/222978185-6d7153ec-b763-4b2a-8b71-31f4eaedb2a5.jpg)

![Screenshot_2023-03-05-19-12-58-880_host.exp.exponent.jpg](https://user-images.githubusercontent.com/43524162/222978192-d61c41b1-dcfd-4f44-803d-52210f3396f6.jpg)

2023-03-07 08:48 UTC, toto04 commented
ok allora _credo_ di aver trovato un workaround, chiaramente anche questa cosa è legata allo stesso problema dei modali, quando l'SVG in qualche modo cambia, il canvas in mode default su Android non si aggiorna correttamente e sbaglia la posizione del SVG al suo interno.
mettere nel canvas `mode="continuous"` fixa la cosa ma ho paura che dia una bella botta alla performance, perciò mi sono inventato questo hack orribile in cui per il primo render dopo un aggiornamento del SVG butta via il canvas e tramite un `setImmediate` causa un aggiornamento dello state nel prossimo ciclo dell'event loop javascript.
In pratica credo che il risultato sia che per uno e un singolo frame tutte le ombre sono `null` e non vengono renderizzate, per poi venir ricostruite nel frame successivo, sembra funzionare (?) forse (?) di nuovo non sono più riuscito a riprodurre la cosa sull'emulatore

per quanto riguarda le ombre chiare boh, sono letteralmente i valori presi da figma, sono effettivamente chiarissime in light mode, si vedono a malapena, ma immagino in realtà è consistente su figma quindi è così da design e non faccio domande ahah

2023-03-07 18:07 UTC, DiegoZaff requested changes
Il workaround che hai trovato sembra funzionare bene! Per il resto ho trovato solo un paio di cose da aggiustare. 

Il commento sul colore dell'ombra vedi te hahah

2023-03-07 18:07 UTC, DiegoZaff commented on src/components/Groups/ModalGroup.tsx
> +      onClose={props.onClose}
penso ci vada `centerText={true}` per allineare il testo centralmente.

2023-03-07 18:11 UTC, DiegoZaff commented
![Screenshot_2023-03-07-19-10-24-979_host.exp.exponent.jpg](https://user-images.githubusercontent.com/43524162/223511684-34aeca4a-5730-4f5f-8592-f8f36fffc283.jpg)



Immagine per farti vedere come viene tagliato il backdrop senza deviceHeight

2023-03-07 19:39 UTC, toto04 commented on src/components/Modal.tsx
> -        deviceHeight={deviceHeight}
eh non sono molto furbo anch'io a togliere cose a caso ahah

2023-03-07 19:39 UTC, toto04 commented on src/components/ContentWrapperScroll.tsx
> +          blur: isLight ? 19 : 32,
Si allora innanzitutto sta cosa c'è anche su iOS, è il rendering che viene così boh, il motivo è molto semplice: so il cazzo di come funziona skia internamente e come funziona il rendering di SVG, che a quanto pare è complicato lol.
Soluzione non bellissima: lasciamo così per il momento, e classifichiamo sta cosa come lievissimo bug da fixare con calma, perché dopo una (non poi così) intensa ricerca su come funzionano i filtri SVG ho capito che non ci capisco un cazzo e andrebbe riscritto in un modo che sia più ingegnerizzato e non frutto dell'estrapolazione del SVG esportato da figma

chiederemo poi alle designer cosa pensano sia meglio fare, tanto modificarlo è questione di 30 secondi se sappiamo quello che stiamo facendo, problema del futuro

2023-03-09 16:48 UTC, DiegoZaff approved these changes
Mi sembra tutto ok

2023-03-09 16:48 UTC, merged