articles navigator e primi passi (?)
PoliNetworkOrg/PoliFemo pull request #181
Opened 2023-03-04 12:38 UTC by SiJam-s

2023-03-04 12:38 UTC, PoliNetwork-ClickUp commented
Task linked: [CU-861md5jq7 Componente Categoria notifiche](https://app.clickup.com/t/861md5jq7)

2023-03-05 19:19 UTC, toto04 requested changes
Ok ti ho scritto un paio di modifiche che farei, fortunatamente una PR così piccola mi permette di essere più specifico nelle modifiche che richiedo ahah

Comunque per il momento non ti preoccupare della pagina Notifiche di per se, anche se mi rendo conto è molto semplice e molto vicino a essere completata, guardando la codebase mi sono reso conto che c'è troppo disordine per tutti sti PageWrapper, ContentScroll, ScrollPage & co., che dovrebbero essere omogeneizzati tra loro, quindi prima di proseguire con queste pagine andrà sistemata sta cosa

2023-03-05 19:19 UTC, toto04 commented on src/components/Notifications/Category.tsx
> +    marginTop: "8%",
non mi piacciono troppo sti valori in percentuale, e `top` non serve dentro a questo componente, al massimo sarà il parent ad aggiungere un padding, ad occhio e croce direi che `marginTop` può essere 35 come la distanza che c'è su Figma e al posto di una `width` dai un `marginHorizontal` in pixel, credo tipo 18 dovrebbe andare bene, controlla tu bene tutti i valori

2023-03-05 19:19 UTC, toto04 commented on src/components/Notifications/Category.tsx
> +    backgroundColor: "#424967",
questi valori sarebbe meglio non hardcodarli, anche se il valore non cambia preferisco comunque che preso dalla palette, quindi togli il background color da questi stili e spostalo sopra dove lo usi:
```ts
    <Pressable style={[{ backgroundColor: palette.primary }, styles.container]} onPress={props.onClick}>```

2023-03-05 19:19 UTC, toto04 commented on src/components/Notifications/Category.tsx
> +    backgroundColor: "#FFB544",
stessa cosa di sopra, sposta questo backgroundColor in modo tale che dipenda dalla palette
```ts
        <View style={[{ backgroundColor: palette.accent }, styles.circle]}>

2023-03-05 19:19 UTC, toto04 commented on src/components/Notifications/Category.tsx
> +    top: "-6%",
non usare valori percentuali, potrebbero variare in base alle dimensioni dello schermo
```suggestion
    left: -5,
    top: -8,
```

2023-03-05 19:19 UTC, toto04 commented on src/components/Notifications/Category.tsx
> +    right: "3%",
```suggestion
    top: 19,
    alignSelf: "center",
    right: 22,
```

2023-03-08 11:07 UTC, DiegoZaff commented
In caso si potrebbe anche mergiare dentro #183 quando il componente è pronto.

2023-03-24 20:04 UTC, toto04 submitted a review, later dismissed

2023-03-24 20:14 UTC, toto04 approved these changes

2023-03-24 20:14 UTC, merged