check google
PoliNetworkOrg/PoliFemo pull request #189
Opened 2023-03-14 17:55 UTC by bob27aggiustatutto

2023-03-14 18:16 UTC, lups2000 commented
Funziona?

2023-03-14 21:28 UTC, bob27aggiustatutto commented
per ora no, mi rifaccio a questo commento per questa pr

https://github.com/react-native-community/discussions-and-proposals/issues/610#issuecomment-1467610114

2023-03-15 05:19 UTC, toto04 commented
perché è stata aperta questa nuova pr oltre a #176? che differenza c'è tra il branch check-google e check-gms? posso chiudere #176 e eliminare check-gms?

2023-03-15 05:27 UTC, toto04 commented
comunque mi sa che ti manca questo step https://docs.expo.dev/guides/using-firebase/#install-expo-dev-client
Expo Go non ha dentro di se il codice nativo necessario perché questa cosa funzioni, la soluzione fornita da expo è semplice e sempre la stessa, probabilmente avrebbe funzionato anche con l'altro pacchetto che è stato linkato nell'altra PR, può essere compilato un nuovo freschissimo client che si comporta come Expo Go ma fatto apposta per la nostra app con le dependencies native tipo firebase in questo caso, e installato direttamente sul dispositivo, ci sono le istruzioni sui docs expo

alternativamente dovrebbe funzionare anche: 
- compilare direttamente l'intera app sul dispositivo ma sarebbe scomodo per lo sviluppo
- avviare una build live tramite android studio, anche per questo ci sono le istruzioni dei docs di expo
ma penso che l'expo dev client rimanga l'opzione migliore

2023-03-15 08:12 UTC, bob27aggiustatutto commented
Teniamo aperte entrambe le PR e branch, vediamo se veniamo ad una quadra

2023-03-15 09:49 UTC, toto04 commented
> Teniamo aperte entrambe le PR e branch, vediamo se veniamo ad una quadra

ma non mi sembra ci sia niente di utile nell'altra, a cosa serve?

2023-03-15 11:21 UTC, bob27aggiustatutto commented
> > Teniamo aperte entrambe le PR e branch, vediamo se veniamo ad una quadra
> 
> ma non mi sembra ci sia niente di utile nell'altra, a cosa serve?

solo per sicurezza, se si può archiviare o cosa bene, altrimenti se non si può salvare in nessun modo rimarrà nel mio pc locale

2023-03-15 17:31 UTC, toto04 commented
@DiegoZaff chiedo il tuo intervento per testare questa cosa su un dispositivo fisico Android con veramente installati i google play services come le persone normali

2023-03-15 17:32 UTC, bob27aggiustatutto commented
io confermo che mi esce "google: false" quindi working as intended

attendiamo qualcuno che abbia google installato su android per testare

2023-03-15 17:41 UTC, toto04 commented
Ah giusto per completezza, rapide istruzioni per le build, ci sono diversi script:
```sh
yarn build:dev
```
produce un expo-dev-client che può essere usato al posto di expo go per lo sviluppo, ma col supporto a pacchetti nativi

---
```sh
yarn build
```
produce la build preview che può essere testata sui dispositivi, un apk su android e un ipa su iOS, dove però bisogna configurare il dispositivo con i servizi online apple perché deve essere firmato in un certo modo

---
```sh
yarn build:prod
```
produce una build da produzione, ovvero un App Bundle per android e su iOS qualcosa di praticamente inutile perché non credo si possa installare da nessuna parte, solo caricare su appstoreconnect per l'approvazione

2023-03-15 17:45 UTC, bob27aggiustatutto commented
ho verificato con un altro cell che ha google e funziona

![immagine](https://user-images.githubusercontent.com/120955097/225397313-dbc5fbcc-9927-4967-9b7d-6eaffde11a0a.png)

2023-03-15 17:46 UTC, lups2000 commented
Sono commosso

2023-03-17 17:39 UTC, toto04 requested changes
sicuramente ci sono un paio di cose che vanno modificate per l'approvazione di questa PR, ma in realtà il problema legato alla build con `react-native-firebase` è lo stesso che avevamo con `react-native-device-info`, possiamo valutare tranquillamente quale dei due faccia più al caso nostro

firebase ha un metodo asincrono che è più comodo da usare, mentre device-info ha un metodo async che meh leggermente più scomodo, anche se potrebbe essere chiamato una volta all'avvio e via, non credo che i gms possano scomparire nel mezzo dell'esecuzione lmao

però firebase ha richiesto una serie di cose non proprio comode dal punto di vista della build, come creare due app (una per sistema operativo) all'interno della console di firebase che boh, non usiamo analytics di firebase (ma potremmo volere in futuro magari?)
firebase per la compilazione richiede che siano presenti i file di configurazione `GoogleSerivce-Info.plist` e `google-services.json` che contengono al loro interno api keys di firebase, a quanto pare non è un problema di sicurezza leakare queste chiavi però se qualcun altro prende questo progetto e lo builda dato che è opensource potrebbe non accorgersi di questi file di configurazione e quindi inviare a noi i loro dati di analytics, che di nuovo, non raccogliamo, però idk lol. Mettere i due file di configurazione in .gitignore complicherebbe il build process dato che dovrebbero tipo essere generati a partire da dei secrets o qualcosa del genere e mamma mia che rottura di coglioni. device-info non ha nessuno di questi problemi e una serie di altre funzioni utili.

magari vogliamo considerare l'opzione di usare firebase analytics? ma actually ci sono modi per usarlo senza il paccheto nativo, usando una versione in [puro javascript](https://docs.expo.dev/versions/v47.0.0/sdk/firebase-analytics/)

2023-03-17 17:39 UTC, toto04 commented on src/pages/settings/Settings.tsx
> +    },
invece di avere questo tasto che apre un alert, direi di includere questa informazione aggiungendo una riga alla sezione con le info sull'app nella pagina About

2023-03-17 17:39 UTC, toto04 commented on src/utils/checkGooglePlayServices.ts
> +}
questa cosa deve essere resa un pochino più furba, usando runtime require al posto di un import dentro un try-catch così che non crashi in expo go, e semplicemente fare in modo che in expo go restituisca `true` (o `null` e gestire i casi particolari, ma per lo scopo di questa funzione anche `true` va bene dato che se non siamo sicuri che non ci siano i gms vogliamo comunque tentare il rendering delle mappe)

2023-03-17 17:54 UTC, bob27aggiustatutto commented
Ma la review la stai facendo a te stesso? Io ho fatto il mio, ora devi assegnare qualcuno a chiudere questa PR, se non te stesso

Non io

2023-03-17 18:08 UTC, toto04 commented
perché non te? sono sicuro che ce la puoi fare, sono fix facili :)
giusto per fare il pezzo di merda burocratico, si stanno tutti occupando di altro con priorità più elevata, bisognerebbe tecnicamente passare per clickup per fare le cose ordinate, tutte ste PR aggiuntive finché vuoi occupartene te in più va bene se no convinci ahmed a metterle nel backlog e si infilano nel prossimo sprint ma devi aspettare la prossima review il 2 aprile

2023-04-05 11:41 UTC, toto04 commented
@bob27aggiustatutto controlla con [questo APK](https://polimi365-my.sharepoint.com/:u:/g/personal/10716563_polimi_it/EfyTjKE2yWdGsvKLaR4xbfUBXCBsB1ohOr8B0qekBTvJ9g?e=Hry8QJ) e con l'ultimo commit se nella pagina About appare `GMS: false`

2023-04-07 07:45 UTC, toto04 approved these changes

2023-04-07 07:45 UTC, merged