ErrorMessage.tsx
PoliNetworkOrg/PoliFemo pull request #199
Opened 2023-04-07 14:16 UTC by SiJam-s

2023-04-10 20:40 UTC, PoliNetwork-ClickUp commented
Task linked: [CU-861mktdr3 Componenti Errore & lista vuota](https://app.clickup.com/t/861mktdr3)

2023-04-13 22:27 UTC, SiJam-s commented
ho dubbi su 18inext (mi pare che cosi si chiami). Ho visto che sono stati creati dei "vocalbolari" per diverse sezioni dell'app con una key. Dovrei creare una sezione a parte per gli errori/emptylist o ad esempio aggiungerli ad home?

2023-04-14 06:19 UTC, lups2000 commented
> ho dubbi su 18inext (mi pare che cosi si chiami). Ho visto che sono stati creati dei "vocalbolari" per diverse sezioni dell'app con una key. Dovrei creare una sezione a parte per gli errori/emptylist o ad esempio aggiungerli ad home?

è una cosa molto a sentimento, personalmente gli errori come "Non ci sono aule disponibili" li metterei nel file json relativi alle alle aule libere, cioè "freclass.json". Errori più generici, magari legati alla connessione o a qualche errore del server del poli li metterei in "common.json" che è diciamo dove ho inserito le stringhe più generiche

2023-04-20 09:01 UTC, toto04 requested changes
mentre aspettiamo di ricevere gli svg aggiornati da caterina c'è sta cosa che mi da troppo fastidio ahah, per il resto ottimo è esattamente come lo volevo

2023-04-20 09:01 UTC, toto04 commented on src/components/ErrorMessage.tsx
> +        </BodyText>
questa cosa qui dovrebbe essere diversa, ci dovrebbe essere sopra un po' più grande la scritta "Ops!" normale e "ERRORE" in grassetto, poi _sotto_ invece il messaggio, tre stili separati

2023-05-03 11:30 UTC, toto04 approved these changes

2023-05-03 11:31 UTC, merged