feature/CU-861mppv9x
PoliNetworkOrg/PoliFemo pull request #235
Opened 2023-08-06 19:04 UTC by M1CH373

Implementation gradingBook

2023-08-06 19:04 UTC, M1CH373 commented
Task linked: [CU-861mppv9x Pagina "libretto"](https://app.clickup.com/t/861mppv9x)

2023-09-19 15:15 UTC, lups2000 commented
@M1CH373 cosa manca in questo branch per essere mergiato?

2023-09-19 15:19 UTC, M1CH373 commented
È ultimata e può essere mergiata, dovresti chiedere a @toto04 se ci sta qualche motivo per cui ancora non è stata mergiata

2023-09-21 08:14 UTC, toto04 requested changes
Ok allora, ci sono un po' di cose che mi turbano, sono tutti dettagli grafici fondamentalmente, molto buono l'ordine in generale nella gestione dei componenti e l'utilizzo degli hook, codice molto pulito mi piace, perdonami la quantità massiccia di commenti ma ci vuole un po' di perfezionismo per creare un'app che sia veramente bella da usare ahah

2023-09-21 08:14 UTC, toto04 commented on src/pages/GradingBook.tsx
> +
invece di restituire null, che fa renderizzare una pagina completamente bianca, renderizza comunque la pagina con il titolo ma mostra un avviso di caricamento / errore

per esempio si potrebbe fare il caricamento tipo:

```suggestion
  const [careerStats, loading] = useApiCall(
    api.gradingbook.getGradingBook,
    { matricola: matricola ?? "" },
    [loggedIn],
    {},
    !loggedIn
  )

  return (
    <PageWrap title={t("gradingBook_title")}>
      {loading ? (
        <LoadingIndicator />
      ) : <>
          <Text>
          ...
        </>
      }
  )
```

e poi se careerStats è null anche mentre non sta caricando puoi mostrare un ErrorMessage col bel faccino di Polifemo

2023-09-21 08:14 UTC, toto04 commented on src/utils/colors.ts
> +  cfuCirle: "#8791bd",
qua il team di design ha lievemente sbagliato nel senso che hanno messo la pallina sotto di un colore diverso del grafico che è un errore, il cerchio è di colore primary, se vuoi puoi scegliere di mettere qua dentro l'altro colore, ma questa è la palette, dai nomi ai colori tipo "tertiary", altrimenti se sono colori per un uso specifico vanno nell'interface ColorTheme

SE decidi comunque di tenere i colori qui dentro però usali, non hardcodarli sia qui che nel componente, nel componente puoi fare 
```ts
import { palette } from "utils/colors"

...

color: palette.tertiary;
```

2023-09-25 18:44 UTC, lups2000 commented
Da iPhone,  ora vedo i valori di “CFU frequentati” e “Esami dati” sballati, cioè non allineati

2023-10-08 13:13 UTC, lups2000 commented
funziona e a me piace il colore nuovo che hai aggiunto, per me possiamo mergiarla

2023-10-08 13:21 UTC, lups2000 approved these changes

2023-10-08 21:38 UTC, toto04 approved these changes

2023-10-08 21:40 UTC, merged