bug should be fixed
PoliNetworkOrg/PoliFemo pull request #236
Opened 2023-08-07 07:24 UTC by lups2000

2023-08-07 07:24 UTC, PoliNetwork-ClickUp commented
Task linked: [CU-8677vbtfq [BUG] mappa delle aule inizia alle coordinate null, null su android](https://app.clickup.com/t/8677vbtfq)

2023-09-14 07:28 UTC, lups2000 commented
Sto aspettando che qualcuno faccia la review e testi, dovrebbe essere fidata definitivamente @angeousta

2023-09-18 17:52 UTC, DiegoZaff requested changes
Allora, c'è qualcosa che non va. In sostanza, sembra funzionare solo perchè ogni volta setta l'ultima posizione corrente tramite

```useEffect(() => {
     AsyncStorage.getItem("lastRegionVisited")
      .then(regionJSON => {
        if (regionJSON) {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
          const tempRegion: Region = JSON.parse(regionJSON)
          setRegion(tempRegion)
        }
      })
      .catch(err => console.log(err))
  }, [])
```


se togliamo questo useEffect torniamo in Africa, quindi la posizione attuale non viene mai utilizzata (questa cosa non dovrebbe accadere imo).

Pensandoci bene, non mi sembra comunque il funzionamento ideale impostare l'ultima posizione visualizzata sempre. Mettiamo che alcuni giorni vado a bovisa e altri vado a leonardo, non voglio ogni volta scorrere col dito tutta milano. Vorrei che quando vado a Leonardo, la prima volta che apro l'app, mi setta la posizione corrente, e finchè non chiudo l app mi salva l'ultima posizione corrente (A leonardo); quando vado a Bovisa, appena apro l'app voglio trovarmi a Bovisa (e finchè non la chiudo si ricorda l'ultima posizione corrente).
Cosa ne dici di questa idea?

Questo comportamento potremmo ottenerlo nel seguente modo:
1) Utente apre app
2) Utente va in ricerca aule tramite posizione
3) Calcoliamo la posizione corrente
4) Settiamo la regione nella mappa
5) Salviamo quella regione nello stato dell'app (ad esempio tramite un provider globale, e non tramite l'async storage com'è adesso)
6) Ogni volta che cambia la regione la settiamo nello stato.
7) Se l'utente esce dalla ricerca tramite posizione e ci rientra mostriamo l'ultima posizione corrente che c'è nello stato, se non c'è niente vuol dire che è la prima volta che l'utente entra nella ricerca delle aule tramite posizione (e quindi siamo al punto 3.)
8) Se l'utente esce dall'app torniamo al punto 1.

Dimmi cosa ne pensi di questo flusso.

Proporrei di cambiare del codice dentro Map.tsx in questo modo:

```
//initialize timer
  let timer: NodeJS.Timeout

  useEffect(() => {
    /* console.log("user latitude changed")
    console.log(props.userLatitude) */

    if (props.userLatitude === 0 && props.userLongitude === 0) {
      clearTimeout(timer)
      timer = setTimeout(() => {
        setError(true)
      }, 10000) //after 10 sec I set the timer to true and I display an error.
    } else {
      clearTimeout(timer)

      /*
        codice per guardare se l'ultima posizione corrente è settata nel provider...

        if(true){
          setta la regione
        }

        altrimenti setta la regione corrente...
      */

      setRegion({
        latitude: props.userLatitude,
        longitude: props.userLongitude,
        latitudeDelta: 0.002,
        longitudeDelta: 0.002,
      })
    }
  }, [props.userLatitude])
```

E' importante che l'useEffect abbia come dipendenza una delle coordinate.

Ho rinominato il timer e setTimer che c'era prima in

```
const [error, setError] = useState<boolean>(false)
```

poichè ho usato il nome timer per inizializzare e usare un timer, in modo che non scatti quando non dovrebbe cancellandolo all'occorrenza.

-----------------------------------------------

Ho trovato una cosa spiacevole dentro `onRegionChangeComplete`, bisogna togliere la riga `setRegion(region)` altrimenti si crea un loop infinito di riaggiornamento della mappa T.T . Con questa modifica sembra anche essere tutto più fluido! Mi era sfuggito ai tempi di quando avevamo fatto la ricerca delle aule hahahah

-----------------------------------------------

dunque queste righe le cancellerei definitivamente:

```
useEffect(() => {
       AsyncStorage.getItem("lastRegionVisited")
      .then(regionJSON => {
        if (regionJSON) {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
          const tempRegion: Region = JSON.parse(regionJSON)
          setRegion(tempRegion)
        }
      })
      .catch(err => console.log(err))
  }, [])
```

2023-09-19 16:39 UTC, DiegoZaff requested changes
Mi sembra andare bene! Sono rimaste 5 righe da togliere dentro il pressable per ios per il salvataggio della region dentro l'async storage (123-126). Dopo di che per me si può mergiare.

Qualcuno con ios può testare se funziona tutto correttamente? @toto04 ?

2023-09-20 06:15 UTC, lups2000 commented
hai ragione, me lo sono perso . thanks @DiegoZaff

2023-09-20 07:45 UTC, DiegoZaff approved these changes

2023-09-21 08:21 UTC, toto04 commented
su iOS funziona tutto perfettamente senza problemi, bella soluzione!

2023-09-21 08:22 UTC, merged