fix hardware back button
PoliNetworkOrg/PoliFemo pull request #266
Opened 2023-11-19 15:03 UTC by M1CH373

2023-11-19 15:16 UTC, M1CH373 commented
Task linked: [CU-8678q8811 [BUG] Nella schermata news il tasto indetro del telefono chiude l'app](https://app.clickup.com/t/8678q8811)

2023-12-06 21:14 UTC, DiegoZaff requested changes

2023-12-06 21:14 UTC, DiegoZaff commented on src/components/Home/News/NewsBottomSheet.tsx
> +
Va molto bene, l'unica cosa è che penso sia meglio lasciare il comportamento di default quando `isNewsClosed === true`.

In modo che premendo il tasto back dalla home con le news chiuse si esca dall'applicazione, come accade in tutte le app, cosa ne pensi?

Ho visto che sembra essere necessario utilizzare un useRef,altrimenti isNewsClosed non riflette i cambiamenti dentro il callback.

Circa cosi:

```
  const [isNewsClosed, setIsNewsClosed] = useState(false)
  const isNewsClosedRef = useRef(isNewsClosed)
  // ...

useEffect(() => {
    // dispatch news sheet event
    newsSheetEventEmitter.emit("state_change", !isNewsClosed)
    isNewsClosedRef.current = isNewsClosed
  }, [isNewsClosed])

  //...

  // dentro il callback
   if (isNewsClosedRef.current == false) {
          setIsNewsClosed(true)
          return true
        }
        return false   
```

2023-12-08 08:00 UTC, DiegoZaff approved these changes
Perfetto 👍

2023-12-09 12:18 UTC, toto04 approved these changes

2023-12-09 12:18 UTC, merged