DateTimePicker
PoliNetworkOrg/PoliFemo pull request #96
Opened 2023-01-08 14:26 UTC by DiegoZaff

2023-01-08 14:26 UTC, PoliNetwork-ClickUp commented
Task linked: [CU-861m3wffu Pagina Aule Libere](https://app.clickup.com/t/861m3wffu)

2023-01-08 14:26 UTC, PoliNetwork-ClickUp commented
Task linked: [CU-861m3wfgq Selettore Data-Ora](https://app.clickup.com/t/861m3wfgq)

2023-01-10 10:10 UTC, lups2000 requested changes

2023-01-10 10:19 UTC, lups2000 commented
Non so per quale motivo ma ti avevo aggiunto anche un altro commento che però non trovo, te lo riscrivo qua!
Praticamente ho provato a testare un pò e funziona, però supponiamo ad esempio di voler trovare le aule libere a partire dalle 18 del 30/01/23. Ho selezionato 30/01/23 e fin qua okay, poi seleziono l'orario, lo confermo e lo schermo mi mostra la data odierna e l'orario 18:00.Stessa cosa se ora provo a riselezionare 30/01/23. Mi mostra la data 30/01/23 con l'ora attuale.
Per semplicità non sarebbe meglio usare la mode "datetime" cosi sia che clicchi sulla data sia sull'orario si apre il modale per selezionare entrambi e finisce lì!Fammi sapere che ne pensi :)

2023-01-11 06:15 UTC, toto04 commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +                    </Text>
il valore di default del fontweight di BodyText è già 400, non serve specificarlo, però si forse è un po' strano che Text sia bold di default in primo luogo 🤔

2023-01-11 06:27 UTC, toto04 requested changes

2023-01-11 06:27 UTC, toto04 commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +                onCancel={hideDateOrTimePicker}
come ti ha segnalato Matteo, sarebbe utile che la data del picker partisse da quella selezionata
```suggestion
                onCancel={hideDateOrTimePicker}
                date={props.date}
```

2023-01-11 06:27 UTC, toto04 commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +        console.log("A date has been picked: ", date)
diego te e i console log 😭
no srsly tho, cerchiamo di lasciare solo log che possano essere in qualche modo utili per diagnostica in caso ci siano problemi dell'app, e spero per dio che non sia un datepicker a rompere l'app lmao

2023-01-11 06:30 UTC, toto04 commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +            />
cosa succede all'api se viene chiamata con una data del passato? o ancora meglio, cosa succede al sito del poli se viene chiesto l'elenco delle aule libere in una data passata?
perché se funziona tipo storico delle aule libere a me va anche bene lasciarlo, un po' inutile ma sti cazzi

2023-01-11 06:31 UTC, toto04 commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +                    <DateTimeBox value={day} />
+1
che fine hanno fatto i puntini :(

2023-01-11 20:35 UTC, DiegoZaff commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +                    <DateTimeBox value={day} />
Ah. Si mi è completamente sfuggito grazie!

2023-01-11 20:38 UTC, DiegoZaff commented
> Non so per quale motivo ma ti avevo aggiunto anche un altro commento che però non trovo, te lo riscrivo qua! Praticamente ho provato a testare un pò e funziona, però supponiamo ad esempio di voler trovare le aule libere a partire dalle 18 del 30/01/23. Ho selezionato 30/01/23 e fin qua okay, poi seleziono l'orario, lo confermo e lo schermo mi mostra la data odierna e l'orario 18:00.Stessa cosa se ora provo a riselezionare 30/01/23. Mi mostra la data 30/01/23 con l'ora attuale. Per semplicità non sarebbe meglio usare la mode "datetime" cosi sia che clicchi sulla data sia sull'orario si apre il modale per selezionare entrambi e finisce lì!Fammi sapere che ne pensi :)

Okay giusto, questa cosa va fixata. Proverei a tenerli separati però dato che la maggior parte delle volte verrano cercate aule libere per il giorno stesso, far risettare anche il giorno ogni volta risulterebbe un po' scomodo imo.

2023-01-11 20:39 UTC, DiegoZaff commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +                onCancel={hideDateOrTimePicker}
Okok

2023-01-11 21:10 UTC, DiegoZaff commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +            />
Dal sito del poli pare possibile la ricerca aule nel passato.

2023-01-11 21:29 UTC, DiegoZaff commented
Ho notato che si è creato un bug strano. Quando confermo data oppure ora riappare il modale un altra volta.
Penso sia dovuto all'aggiunta di props.date al DateTimePickerModal (anche perchè di logica è cambiato solo quello). Cerco di fixare nel prox commit.

2023-01-17 09:34 UTC, toto04 approved these changes

2023-01-17 09:39 UTC, toto04 commented on src/components/FreeClass/DateTimePicker/DateTimePicker.tsx
> +                    </Text>
ok direi che questa è una cosa che guarderemo nel futuro, per il momento va been come hai fatto tu, ci possiamo pensare dopo la prima beta

2023-01-17 09:44 UTC, toto04 commented
Lascio a Matteo l'onore di inserire il date picker in tutte le pagine gestendo lo state come crede meglio, for the record per il momento è inserito solo nella pagina CampusChoice.tsx

2023-01-17 09:44 UTC, merged